# database.yml
parameters:
  pdo.class: PDO
  pdo.attr_errmode: 3
  pdo.erromode_exception: 2
  pdo.fetch_assoc: 2
  pdo.attr_default_fetch_mode: 19
  pdo.fetch_assoc: 2
  pdo.emulate_prepares: 20
  pdo.false: 0
 
  pdo.options:
    %pdo.attr_errmode%: %pdo.erromode_exception%
    %pdo.attr_default_fetch_mode%: %pdo.fetch_assoc%
    %pdo.emulate_prepares%: %pdo.false%
     
  database.db1.dsn: mysql:database=notes;dbname=notes;host=localhost
  database.db1.username: root
  database.db1.password: 

services:
  db1:
    class: %pdo.class%
    arguments:
      - %database.db1.dsn%
      - %database.db1.username%
      - %database.db1.password%
      - %pdo.options%