app:
    resource: "@AppBundle/Controller/"
    type:     annotation

main:
    path: /

success:
    path: /success
        
notes:
    path: /notes

add:
    path: /add

delete:
    path: /notes/delete/{id}
    
edit:
    path: /notes/edit/{id}